// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;



/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
import 'firebase_options.dart';
/// // ...
 await Firebase.initializeApp(
   options: DefaultFirebaseOptions.currentPlatform,
 );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAI5X_Vy1kqd0Pog8bNUW8-CbvTiBrnVsY',
    appId: '1:79235184565:web:b083f14a877e65f7f88bfc',
    messagingSenderId: '79235184565',
    projectId: 'flutterfirebase-fd2ca',
    authDomain: 'flutterfirebase-fd2ca.firebaseapp.com',
    storageBucket: 'flutterfirebase-fd2ca.appspot.com',
    measurementId: 'G-YZQCGFNK9E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBd3Jyeni1W46OSIRJFCdQ5Ncc8rkx_ntE',
    appId: '1:79235184565:android:3c610694277115e5f88bfc',
    messagingSenderId: '79235184565',
    projectId: 'flutterfirebase-fd2ca',
    storageBucket: 'flutterfirebase-fd2ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDrcCtZw-ifsPv43vfA73bVaA-srre4FtQ',
    appId: '1:79235184565:ios:94e4ee443fa63d6df88bfc',
    messagingSenderId: '79235184565',
    projectId: 'flutterfirebase-fd2ca',
    storageBucket: 'flutterfirebase-fd2ca.appspot.com',
    iosBundleId: 'com.example.flutterDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDrcCtZw-ifsPv43vfA73bVaA-srre4FtQ',
    appId: '1:79235184565:ios:526a0413aee6298cf88bfc',
    messagingSenderId: '79235184565',
    projectId: 'flutterfirebase-fd2ca',
    storageBucket: 'flutterfirebase-fd2ca.appspot.com',
    iosBundleId: 'com.example.flutterDemo.RunnerTests',
  );
}
